CREATE TABLE IF NOT EXISTS `USER` (
    ID IDENTITY NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(64) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(128) NOT NULL,
    USER_TYPE ENUM('USER','ADMIN')
);

CREATE TABLE IF NOT EXISTS CLIENT (
    CLIENT_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    CLIENT_SECRET_HASH VARCHAR(128) DEFAULT NULL,
    OWNER_ID BIGINT NOT NULL,
    APP_NAME VARCHAR(64) NOT NULL,
    FOREIGN KEY(OWNER_ID) REFERENCES `USER`(ID)
);

CREATE TABLE IF NOT EXISTS CLIENT_REDIRECT_URL (
    CLIENT_ID VARCHAR(64) NOT NULL,
    URL VARCHAR(512) NOT NULL,
    PRIMARY KEY(CLIENT_ID, URL),
    FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(CLIENT_ID)
);

-- rememberme
CREATE TABLE IF NOT EXISTS persistent_logins (
    username VARCHAR(64) NOT NULL,
    series VARCHAR(64) PRIMARY KEY,
    token VARCHAR(64) NOT NULL,
    last_used TIMESTAMP NOT NULL
);
