name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.javaVersion }}
        cache: 'maven'
        distribution: 'temurin'
    - name: Build and run tests
      run: mvn verify